### PR TITLE
Update matrix.h

### PR DESCRIPTION
**Pull request by jakepoz**
Fix an off by one error in matrix_get_row_copy helper function.

### CODE REVIEW

**Comment by sunsided** [comment]
Thanks!

**Comment by jakepoz** [comment]
No problem, I'm still seeing an issue on filters with more states however, where suddenly all the values go to -Infinity in the state vector. Seems to happen upon cholesky decomposition, will try to check into it. 

Very nice C library btw, easy to port to many platforms without dependency hell.

**Comment by jakepoz** [comment]
Nevermind, I think it was a weird platform issue :)

**Comment by sunsided** [comment]
Phew, that's actually a relief! I'm still a bit embarrassed by the index one! :D

Btw., I just released the code under MIT license; thought it would be the most sane thing to do. Since you already contributed - are you okay with that?

**Comment by jakepoz** [comment]
Yup, no problems with that.

**Pull request merged**
